from enum import StrEnum

class FlagStatusEnum(StrEnum):
    ENTREGA_PARCIAL = "ENTREGA_PARCIAL"
    DEVOLUCAO_EQUIPAMENTO = "DEVOLUCAO_EQUIPAMENTO"
    AGUARDANDO_ESTOQUE = "AGUARDANDO_ESTOQUE"
    RETIFICACAO_OFICIO = "RETIFICACAO_OFICIO"
