from enum import StrEnum

class FlagStatusEnum(StrEnum):
    ENTREGA_PARCIAL = "ENTREGA_PARCIAL"
    AGUARDANDO_EMPRESA = "AGUARDANDO_EMPRESA"
    FALTA_EQUIPAMENTO = "FALTA_EQUIPAMENTO"
    PRONTO_PARA_REVISAO = "PRONTO_PARA_REVISAO"
    AGUARDANDO_OFICIO = "AGUARDANDO_OFICIO"
